// next/src/app/chordquizz/page.tsx
'use client'

import { useRouter } from 'next/navigation'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import AppHeader from '@/components/AppHeader'
import ChordSelectionButton from '@/components/ChordSelectionButton'
import FrequencySettings from '@/components/FrequencySettings'
import type { Chord } from '@/constants/chords'
import type { HistoryItem } from '@/types/app'
import { useAppSettings, useAuth, useChordSettings, useFeatures, usePro } from '@/lib/app-context'
import { useAudio } from '@/lib/audio'
import { useChordFrequency } from '@/lib/chord-frequency'
import { decodeCookie, HUNDRED_YEARS, readCookie, writeCookie } from '@/lib/cookie'
import { getSupabase } from '@/lib/supabase'

type QuizChord = Chord & { homeEnabled?: boolean }
type View = 'settings' | 'quiz' | 'result'

const DELAYS = { PLAYBACK_START: 500, TRANSITION: 400, FEEDBACK: 800 }
const QUIZ_COOKIE = 'chord_quizz_settings'

interface QuizCookie {
  selectedChordIds: string[]
  parentChordRatio: number
  isReviewWeighted: boolean
}

const shuffle = <T,>(items: T[]) => {
  const a = [...items]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j]!, a[i]!]
  }
  return a
}

export default function ChordQuizPage() {
  const router = useRouter()
  const { allChords: customChords } = useChordSettings()
  const { formatColorName } = useAppSettings()
  const { userTier, authReady } = useAuth()
  const { hasAccess } = usePro()
  const { isEnabled } = useFeatures()
  const { samplers, selectedInstrument, isSamplerLoaded, loadSampler, playEffect } = useAudio()

  const chords = useMemo<QuizChord[]>(
    () => customChords.slice(0, 14).map((c, i) => ({
      ...c, label: String(i + 1), displayColor: formatColorName(c.colorName), displayColorFormatted: formatColorName(c.colorName), sortOrder: i + 1
    })),
    [customChords, formatColorName]
  )

  const [view, setView] = useState<View>('settings')
  const [score, setScore] = useState(0)
  const [questionIndex, setQuestionIndex] = useState(0)
  const [questions, setQuestions] = useState<QuizChord[]>([])
  const [userAnswer, setUserAnswer] = useState<QuizChord | null>(null)
  const [isQuestionChanging, setIsQuestionChanging] = useState(false)
  const [history, setHistory] = useState<HistoryItem[]>([])
  const [selectedIds, setSelectedIds] = useState<string[]>([])
  const [shuffledIds, setShuffledIds] = useState<string[]>([])
  const [cookiesLoaded, setCookiesLoaded] = useState(false)

  const selectedChords = useMemo(() => chords.filter(c => selectedIds.includes(c.id)), [chords, selectedIds])
  const freq = useChordFrequency(selectedChords)
  const { parentChordRatio, setParentChordRatio, isReviewWeighted, setIsReviewWeighted } = freq

  const currentQuestion = questions[questionIndex]
  const whiteKeyChords = chords.filter(c => (c.sortOrder || 0) <= 9)
  const blackKeyChords = chords.filter(c => (c.sortOrder || 0) > 9)
  const canUseBlackKeys = hasAccess('quiz_content_black_keys', userTier)

  const layoutChords = useMemo(() => (
    view === 'quiz'
      ? shuffledIds.map(id => chords.find(c => c.id === id)).filter((c): c is QuizChord => !!c)
      : selectedChords
  ), [view, shuffledIds, chords, selectedChords])
  const gridCols = layoutChords.length <= 3 ? 1 : layoutChords.length <= 8 ? 2 : 3
  const gridRows = Math.ceil(layoutChords.length / gridCols)

  // Latest values for timers (avoid stale closures)
  const latest = useRef({ questions, questionIndex, samplers, selectedInstrument, isSamplerLoaded, getRandomChord: freq.getRandomChord, selectedIds })
  latest.current = { questions, questionIndex, samplers, selectedInstrument, isSamplerLoaded, getRandomChord: freq.getRandomChord, selectedIds }
  const timers = useRef<ReturnType<typeof setTimeout>[]>([])
  const later = (fn: () => void, ms: number) => { timers.current.push(setTimeout(fn, ms)) }

  const goSubscription = () => {
    if (confirm('このオプションの変更はPROプラン限定です。プランを確認しますか？')) router.push('/subscription')
  }

  // --- Persistence ------------------------------------------------------------
  useEffect(() => {
    if (!authReady) return
    const saved = decodeCookie<Partial<QuizCookie>>(JSON.stringify(readCookie(QUIZ_COOKIE, {})), {})
    let ids = saved.selectedChordIds ?? []
    if (ids.length === 0 && chords.length >= 2) ids = [chords[0]!.id, chords[1]!.id]
    setSelectedIds(ids)
    if (saved.parentChordRatio !== undefined) setParentChordRatio(saved.parentChordRatio)
    if (saved.isReviewWeighted !== undefined) setIsReviewWeighted(saved.isReviewWeighted)
    setCookiesLoaded(true)

    let preferred = (readCookie<{ instrument?: string }>('zettaionkan_app_settings', {}).instrument || 'yamaha') as 'yamaha' | 'steinway'
    if (preferred === 'steinway' && userTier !== 'premium') preferred = 'yamaha'
    loadSampler(preferred)

    new Image().src = '/quiz_correct.png'
    new Image().src = '/quiz_incorrect.png'
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [authReady])

  useEffect(() => {
    if (!cookiesLoaded) return
    writeCookie(QUIZ_COOKIE, { selectedChordIds: selectedIds, parentChordRatio, isReviewWeighted } satisfies QuizCookie, HUNDRED_YEARS)
  }, [cookiesLoaded, selectedIds, parentChordRatio, isReviewWeighted])

  useEffect(() => () => timers.current.forEach(clearTimeout), [])

  // --- Core logic -------------------------------------------------------------
  const playQuestion = useCallback(async () => {
    const { questions, questionIndex, samplers, selectedInstrument, isSamplerLoaded } = latest.current
    const sampler = samplers[selectedInstrument]
    const chord = questions[questionIndex]
    if (!sampler || !isSamplerLoaded || !chord) return
    const Tone = await import('tone')
    if (Tone.getContext().state !== 'running') await Tone.start()
    sampler.triggerAttackRelease(chord.notes, 8)
  }, [])

  const toggleChordSelection = (id: string) => {
    const target = chords.find(c => c.id === id)
    if (!target) return
    if ((target.sortOrder || 0) > 9 && !canUseBlackKeys) { goSubscription(); return }
    // Selecting level N selects levels 1..N
    setSelectedIds(chords.filter(c => (c.sortOrder || 0) <= (target.sortOrder || 0)).map(c => c.id))
  }

  const startQuiz = () => {
    timers.current.forEach(clearTimeout)
    const first = freq.getRandomChord()
    const qs = first ? [first] : []
    latest.current.questions = qs
    latest.current.questionIndex = 0
    setQuestions(qs)
    setQuestionIndex(0)
    setScore(0)
    setHistory([])
    setUserAnswer(null)
    setShuffledIds(shuffle(selectedIds))
    setView('quiz')
    // Let the browser Back button return to the settings instead of leaving the page
    window.history.pushState({ quiz: true }, '')
    later(playQuestion, DELAYS.PLAYBACK_START)
  }

  const advance = (delay: number) => {
    setIsQuestionChanging(true)
    later(() => {
      const next = latest.current.getRandomChord()
      const qs = next ? [...latest.current.questions, next] : latest.current.questions
      latest.current.questions = qs
      latest.current.questionIndex += 1
      setQuestions(qs)
      setQuestionIndex(latest.current.questionIndex)
      setUserAnswer(null)
      setIsQuestionChanging(false)
      setShuffledIds(shuffle(latest.current.selectedIds))
      // wait for state to flush before playing the new question
      later(playQuestion, 0)
    }, delay)
  }

  const submitAnswer = (chord: QuizChord) => {
    if (userAnswer || isQuestionChanging || !currentQuestion) return
    const isCorrect = chord.id === currentQuestion.id
    if (isCorrect) setScore(s => s + 1)
    playEffect(isCorrect ? 'correct' : 'incorrect')
    setHistory(h => [...h, { question: { ...currentQuestion }, answer: { ...chord }, isCorrect, isSkipped: false }])
    setUserAnswer(chord)
    advance(DELAYS.FEEDBACK)
  }

  const skipQuestion = () => {
    if (userAnswer || isQuestionChanging || !currentQuestion) return
    setHistory(h => [...h, { question: { ...currentQuestion }, answer: null, isCorrect: false, isSkipped: true }])
    advance(DELAYS.TRANSITION)
  }

  const finishQuiz = async () => {
    timers.current.forEach(clearTimeout)
    const supabase = getSupabase()
    const { data: { user } } = await supabase.auth.getUser()
    if (user && history.length > 0) {
      try {
        await supabase.from('training_sessions').insert({
          user_id: user.id,
          score,
          total_questions: history.length,
          details: history,
          settings: { mode: 'chord_quizz', selected_chords: selectedIds, instrument: selectedInstrument }
        } as never)
      } catch (e) {
        console.error('Failed to save session:', e)
      }
    }
    setView('result')
  }

  const resetQuiz = useCallback(() => {
    timers.current.forEach(clearTimeout)
    setUserAnswer(null)
    setIsQuestionChanging(false)
    setView('settings')
  }, [])

  const viewRef = useRef(view)
  viewRef.current = view
  useEffect(() => {
    const onPop = () => { if (viewRef.current !== 'settings') resetQuiz() }
    window.addEventListener('popstate', onPop)
    return () => window.removeEventListener('popstate', onPop)
  }, [resetQuiz])

  const handleHeaderBack = (e: React.MouseEvent) => {
    if (view !== 'settings') { e.preventDefault(); resetQuiz() }
  }

  const rate = history.length ? score / history.length : 0
  const isCorrectAnswer = !!userAnswer && !!currentQuestion && userAnswer.id === currentQuestion.id

  return (
    <div className="min-h-screen bg-white font-['Noto_Sans_JP'] antialiased">
      <div className="min-h-screen flex flex-col items-center max-w-3xl mx-auto relative overflow-hidden">
        <AppHeader showBack onBack={handleHeaderBack} />

        <main className={`w-full flex-grow flex flex-col ${view === 'quiz' ? 'p-0 overflow-hidden' : 'px-4 py-6 overflow-y-auto'}`} style={{ scrollbarGutter: 'stable' }}>
          {/* SETTINGS */}
          {view === 'settings' && (
            <div className="space-y-8 pb-40">
              <div className="text-center mb-2">
                <h2 className="text-xl font-black text-gray-900">和音クイズ</h2>
                <p className="text-xs text-gray-400 mt-1 font-bold">覚えた色をテストしてみましょう</p>
              </div>

              <div className="px-2 space-y-3">
                <button
                  type="button"
                  onClick={startQuiz}
                  disabled={selectedIds.length === 0}
                  className="w-full py-4 bg-gray-900 text-white font-bold rounded-2xl shadow-xl hover:bg-gray-800 transition-all active:scale-95 disabled:opacity-50 disabled:scale-100 flex items-center justify-center space-x-2 border-b-4 border-gray-700"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z" clipRule="evenodd" />
                  </svg>
                  <span>テストを開始する</span>
                </button>
              </div>

              <section>
                <div className="flex items-center justify-between mb-4 px-1">
                  <span className="text-xs font-bold text-gray-400 uppercase tracking-widest">出題する和音</span>
                </div>

                <div className="mb-6">
                  <h3 className="text-xs font-bold text-gray-900 mb-3 flex items-center"><span className="w-1 h-4 bg-gray-900 rounded-full mr-2" />白鍵の和音</h3>
                  <div className="grid grid-cols-2 gap-3">
                    {whiteKeyChords.map(c => (
                      <ChordSelectionButton key={c.id} chord={c} selected={selectedIds.includes(c.id)} onToggle={() => toggleChordSelection(c.id)} onLockedClick={goSubscription} />
                    ))}
                  </div>
                </div>

                <h3 className="text-xs font-bold text-gray-900 mb-4 flex items-center"><span className="w-1 h-4 bg-gray-900 rounded-full mr-2" />黒鍵の和音</h3>
                <div className="grid grid-cols-2 gap-3">
                  {blackKeyChords.map(c => (
                    <ChordSelectionButton
                      key={c.id} chord={c} selected={selectedIds.includes(c.id)} locked={!canUseBlackKeys}
                      onToggle={() => toggleChordSelection(c.id)}
                      onLockedClick={() => { if (confirm('黒鍵（レベル10〜14）はPROプラン限定です。\nプラン詳細を確認しますか？')) router.push('/subscription') }}
                    />
                  ))}
                </div>
              </section>

              {isEnabled('quiz_settings_frequency') && (
                <FrequencySettings
                  parentChordRatio={parentChordRatio} onParentChordRatioChange={setParentChordRatio}
                  isReviewWeighted={isReviewWeighted} onReviewWeightedChange={setIsReviewWeighted}
                  parentChord={freq.parentChord} otherChords={freq.otherChords}
                  otherChordsDisplay={freq.otherChordsDisplay} otherChordsWithWeights={freq.otherChordsWithWeights}
                  selectedCount={selectedChords.length}
                />
              )}
            </div>
          )}

          {/* QUIZ */}
          {view === 'quiz' && (
            <div className="flex-grow w-full flex flex-col bg-white relative">
              <div className="fixed top-0 left-0 right-0 z-[60] h-1.5 bg-gray-100/50 backdrop-blur-sm">
                <div className={`h-full w-full bg-indigo-500 shadow-[0_0_10px_rgba(99,102,241,0.5)] transition-all duration-500 ease-out ${isQuestionChanging ? 'brightness-150 h-2' : ''}`} />
              </div>

              <div className="absolute top-4 left-4 right-4 z-50 flex justify-between items-center pointer-events-none">
                <div className={`flex items-center bg-black/40 backdrop-blur-md rounded-full border border-white/10 shadow-lg overflow-hidden ring-1 ring-black/5 h-8 transition-all duration-300 ${isQuestionChanging ? 'scale-125 ring-4 ring-indigo-500/50 bg-indigo-900/60' : ''}`}>
                  <div className="px-3 h-full flex items-center bg-white/10 border-r border-white/5">
                    <span className="text-[8px] text-gray-300 font-black uppercase tracking-widest leading-none">Question</span>
                  </div>
                  <div className="px-4 h-full flex items-center min-w-[3rem] justify-center text-white text-[11px] font-black">Q {questionIndex + 1}</div>
                </div>
                <button type="button" onClick={finishQuiz} className="pointer-events-auto bg-black/40 backdrop-blur-md text-[10px] text-white font-black rounded-full px-4 h-8 hover:bg-black/50 transition-colors border border-white/10 shadow-lg flex items-center">
                  テストを終了
                </button>
              </div>

              {userAnswer && (
                <div className="fixed inset-0 z-[100] flex items-center justify-center pointer-events-none" aria-live="polite">
                  <div className={`text-[250px] sm:text-[350px] font-black select-none leading-none ${isCorrectAnswer ? 'text-blue-500 drop-shadow-[0_0_20px_rgba(59,130,246,0.6)]' : 'text-red-500 drop-shadow-[0_0_20px_rgba(239,68,68,0.6)]'}`}>
                    {isCorrectAnswer ? '◯' : '×'}
                  </div>
                </div>
              )}

              <div
                key={questionIndex}
                className="flex-grow grid gap-0.5 w-full h-full"
                style={{ gridTemplateColumns: `repeat(${gridCols}, minmax(0, 1fr))`, gridTemplateRows: `repeat(${gridRows}, minmax(0, 1fr))` }}
              >
                {layoutChords.map(chord => (
                  <button
                    key={chord.id}
                    type="button"
                    onClick={() => submitAnswer(chord)}
                    disabled={!!userAnswer}
                    aria-label={chord.colorName}
                    className={`relative w-full h-full transition-all duration-150 active:scale-95 flex items-center justify-center overflow-hidden ${userAnswer ? (userAnswer.id === chord.id ? 'z-10 ring-inset ring-8 ring-white/50' : 'opacity-20') : 'hover:brightness-105 active:brightness-90'}`}
                    style={{ backgroundColor: chord.color }}
                  />
                ))}
              </div>

              <div className="absolute bottom-10 left-0 right-0 z-50 flex justify-center items-center space-x-4 pointer-events-none">
                <button type="button" onClick={playQuestion} className="pointer-events-auto bg-black/40 backdrop-blur-md text-[10px] text-white font-black rounded-full px-6 py-2.5 hover:bg-black/50 transition-colors border border-white/20 shadow-lg flex items-center space-x-2 active:scale-95">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fillRule="evenodd" d="M4 2a1 1 0 011 1v2.101a7.002 7.002 0 0111.601 2.566 1 1 0 11-1.885.666A5.002 5.002 0 005.999 7H9a1 1 0 010 2H4a1 1 0 01-1-1V3a1 1 0 011-1zm.008 9.057a1 1 0 011.276.61A5.002 5.002 0 0014.001 13H11a1 1 0 110-2h5a1 1 0 011 1v5a1 1 0 11-2 0v-2.101a7.002 7.002 0 01-11.601-2.566 1 1 0 01.61-1.276z" clipRule="evenodd" />
                  </svg>
                  <span>もう一度聴く</span>
                </button>
                <button type="button" onClick={skipQuestion} className="pointer-events-auto bg-black/40 backdrop-blur-md px-6 py-2.5 rounded-full text-white font-black hover:bg-black/50 transition-all flex items-center space-x-2 active:scale-95 border border-white/10 shadow-lg">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 5l7 7-7 7M5 5l7 7-7 7" />
                  </svg>
                  <span className="text-[10px] uppercase tracking-widest">スキップ</span>
                </button>
              </div>
            </div>
          )}

          {/* RESULT */}
          {view === 'result' && (
            <div className="h-full flex flex-col items-center">
              <div className="mb-8 text-center pt-8">
                <p className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-2">Quiz Finished</p>
                <div className="text-6xl font-black text-gray-900 mb-2">
                  <span className="text-blue-500">{score}</span>
                  <span className="text-gray-300 text-4xl">/{history.length}</span>
                </div>
                <p className="text-lg font-bold text-gray-600 mb-6">
                  {score === history.length ? 'Perfect! 🎉' : rate >= 0.8 ? 'Great Job! 👍' : 'Keep Practicing! 💪'}
                </p>
              </div>

              <div className="w-full bg-gray-50 rounded-3xl border border-gray-100 mb-10 overflow-hidden flex flex-col max-h-[400px]">
                <div className="px-6 py-4 border-b border-gray-100 flex justify-between items-center bg-white/50">
                  <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">解答履歴</span>
                  <span className="text-[10px] font-bold text-gray-900">{score} / {history.length} 正解</span>
                </div>
                <div className="flex-grow overflow-y-auto px-4 py-2 space-y-2">
                  {history.map((h, idx) => (
                    <div key={idx} className="flex items-center space-x-4 p-3 rounded-2xl bg-white border border-gray-100">
                      <div className="w-8 h-8 rounded-full border border-gray-100 flex items-center justify-center text-[10px] font-black text-gray-400 shrink-0">{idx + 1}</div>
                      <div className="flex-grow flex items-center space-x-3 min-w-0">
                        <div className="flex flex-col items-center space-y-1">
                          <div className="w-10 h-10 rounded-lg shadow-sm shrink-0" style={{ backgroundColor: (h.question as Chord).color }} />
                          <span className="text-[8px] font-bold text-gray-400 leading-none">正解</span>
                        </div>
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                        </svg>
                        <div className="flex flex-col items-center space-y-1">
                          {h.answer ? (
                            <div className="w-10 h-10 rounded-lg shadow-sm shrink-0" style={{ backgroundColor: (h.answer as Chord).color }} />
                          ) : (
                            <div className="w-10 h-10 rounded-lg border-2 border-dashed border-gray-200 flex items-center justify-center shrink-0">
                              <span className="text-[8px] text-gray-300 font-bold">SKIP</span>
                            </div>
                          )}
                          <span className="text-[8px] font-bold text-gray-400 leading-none">回答</span>
                        </div>
                      </div>
                      <div className="shrink-0 w-10 flex justify-center">
                        {h.isCorrect ? <span className="text-green-500 font-black text-xl">○</span>
                          : h.isSkipped ? <span className="text-gray-300 font-bold text-sm">−</span>
                            : <span className="text-red-500 font-black text-xl">×</span>}
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div className="w-full space-y-4 px-6 mb-20">
                <button type="button" onClick={startQuiz} className="w-full py-4 bg-gray-900 text-white font-bold rounded-2xl shadow-lg hover:bg-gray-800 transition-all active:scale-95">もう一度挑戦する</button>
                <button type="button" onClick={resetQuiz} className="w-full py-4 bg-white text-gray-900 font-bold rounded-2xl border border-gray-200 hover:bg-gray-50 transition-all active:scale-95">設定に戻る</button>
              </div>
            </div>
          )}
        </main>
      </div>
    </div>
  )
}

// app/pages/chordquizz.vue
<script setup lang="ts">
import type { Database } from '~/types/database.types'
const supabase = useSupabaseClient<Database>()

import * as Tone from 'tone'
import { ChordDefinitions, type Chord } from '~/constants/chords'
import type { HistoryItem } from '~/types/app'



const router = useRouter()

// === Constants ===
const { allChords: customChords } = useChordSettings()
const { namingConvention, formatChordName, formatColorName } = useAppSettings()

const QUIZZ_CHORDS = computed<Chord[]>(() => {
  return customChords.value.slice(0, 14).map((c, index) => ({
    ...c,
    label: (index + 1).toString(),
    displayColor: formatColorName(c.colorName),
    displayColorFormatted: formatColorName(c.colorName),
    sortOrder: index + 1
  }))
})

// const QUIZ_LENGTH = 5 (Endless mode)

const DELAYS = {
  PLAYBACK_START: 500,
  TRANSITION: 400,
  FEEDBACK: 800
}

// === Reactive State ===
const view = ref('settings')
const score = ref(0)
const isSaving = ref(false)
const currentQuestionIndex = ref(0)
const resultMessage = ref<string | null>(null)
const userAnswer = ref<Chord | null>(null)
const isQuestionChanging = ref(false)

const selectedChordIds = ref(new Set())
const questions = ref<Chord[]>([])
const quizzHistory = ref<HistoryItem[]>([])
const shuffledIds = ref<string[]>([])
const correctHistory = computed(() => quizzHistory.value.filter(h => h.isCorrect))

const selectedChords = computed(() => {
  return QUIZZ_CHORDS.value.filter(c => selectedChordIds.value.has(c.id))
})

const {
  parentChordRatio,
  isReviewWeighted,
  parentChord,
  otherChords,
  otherChordsDisplay,
  otherChordsWithWeights,
  getRandomChord
} = useChordFrequency(selectedChords)

const { user, userTier, authReady } = useAuth()
const { hasAccess, isEnabled, isPro: checkProAccess } = usePro()
const checkAccess = (feature: any) => hasAccess(feature, userTier.value)
const isPro = computed(() => checkProAccess(userTier.value))

const navigateToSubscription = () => {
    if (confirm('このオプションの変更はPROプラン限定です。プランを確認しますか？')) {
        router.push('/subscription')
    }
}

const handleLockedClick = () => {
  if (confirm('黒鍵（レベル10〜14）はPROプラン限定です。\nプラン詳細を確認しますか？')) {
    router.push('/subscription')
  }
} // Temporary simple alert


const { 
  samplers, 
  isLoading, 
  loadingProgress, 
  isSamplerLoaded, 
  selectedInstrument, 
  loadSampler,
  playEffect
} = useAudio()

// === Computed ===
const currentQuestion = computed(() => questions.value[currentQuestionIndex.value])
const currentQuestionCount = computed(() => currentQuestionIndex.value + 1)
const isAllSelected = computed(() => selectedChordIds.value.size > 0)
const whiteKeyChords = computed(() => QUIZZ_CHORDS.value.filter(c => (c.sortOrder || 0) <= 9))
const blackKeyChords = computed(() => QUIZZ_CHORDS.value.filter(c => (c.sortOrder || 0) > 9))
const currentLayoutChords = computed(() => {
  if (view.value === 'quiz') {
    return shuffledIds.value.map(id => QUIZZ_CHORDS.value.find(c => c.id === id)).filter((c): c is Chord => !!c) as Chord[]
  }
  return QUIZZ_CHORDS.value.filter(c => selectedChordIds.value.has(c.id))
})

// Dynamic Grid Logic
const gridCols = computed(() => {
  const count = currentLayoutChords.value.length
  if (count <= 3) return 1
  if (count <= 8) return 2
  return 3
})

const gridRows = computed(() => {
  return Math.ceil(currentLayoutChords.value.length / gridCols.value)
})

const shuffleChords = () => {
  const ids = Array.from(selectedChordIds.value)
  for (let i = ids.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [ids[i], ids[j]] = [ids[j], ids[i]]
  }
  shuffledIds.value = ids as string[]
}

// === Persistence ===
interface QuizzCookieSettings {
  selectedChordIds: string[]
  parentChordRatio: number
  isReviewWeighted: boolean
}

const quizzCookie = useCookie<QuizzCookieSettings>('chord_quizz_settings', {
  default: () => ({
    selectedChordIds: [],
    parentChordRatio: 0.3,
    isReviewWeighted: false
  }),
  watch: true,
  maxAge: 60 * 60 * 24 * 365 * 100 // 100 years
})

const syncToCookie = () => {
  quizzCookie.value = {
    selectedChordIds: Array.from(selectedChordIds.value) as string[],
    parentChordRatio: parentChordRatio.value,
    isReviewWeighted: isReviewWeighted.value
  }
}

const loadFromCookie = () => {
  const s = quizzCookie.value
  if (s.selectedChordIds) selectedChordIds.value = new Set(s.selectedChordIds)
  if (s.parentChordRatio !== undefined) parentChordRatio.value = s.parentChordRatio
  if (s.isReviewWeighted !== undefined) isReviewWeighted.value = s.isReviewWeighted
}

// === Helper Functions ===
const cleanupSideEffects = () => {
  // No specific timeouts or intervals to clear for now unrelated to auto-play
}

const isLightColor = (hex: string) => {
  if (!hex) return false
  const r = parseInt(hex.slice(1, 3), 16)
  const g = parseInt(hex.slice(3, 5), 16)
  const b = parseInt(hex.slice(5, 7), 16)
  const brightness = (r * 299 + g * 587 + b * 114) / 1000
  return brightness > 180
}

// === Core Logic ===
const playCurrentQuestion = async () => {
  cleanupSideEffects()
  const s = samplers[selectedInstrument.value]
  if (!s || !isSamplerLoaded.value) return
  if (Tone.context.state !== 'running') await Tone.start()
  
  const chord = currentQuestion.value
  if (!chord) return
  s.triggerAttackRelease(chord.notes, 8)
}

const toggleChordSelection = (id: string) => {
  const targetChord = QUIZZ_CHORDS.value.find(c => c.id === id)
  if (!targetChord) return

  const isBlackKey = (targetChord.sortOrder || 0) > 9
  if (isBlackKey && !checkAccess('quiz_content_black_keys')) {
    navigateToSubscription()
    return
  }

  const newSet = new Set()
  QUIZZ_CHORDS.value.forEach(c => {
    if ((c.sortOrder || 0) <= (targetChord.sortOrder || 0)) newSet.add(c.id)
  })
  selectedChordIds.value = newSet
}



const startQuizz = async () => {
  const firstChord = getRandomChord()
  questions.value = firstChord ? [firstChord] : []
  currentQuestionIndex.value = 0
  score.value = 0
  quizzHistory.value = []
  userAnswer.value = null
  shuffleChords() // Initial shuffle
  view.value = 'quiz'
  
  setTimeout(playCurrentQuestion, DELAYS.PLAYBACK_START)
}

const moveNext = () => {
  const nextChord = getRandomChord()
  if (nextChord) questions.value.push(nextChord)
  currentQuestionIndex.value++
  resultMessage.value = null
  shuffleChords() // Shuffle for each question
  
  setTimeout(playCurrentQuestion, DELAYS.TRANSITION)
}

const submitAnswer = (chord: Chord) => {
  if (resultMessage.value) return 
  cleanupSideEffects()

  if (!currentQuestion.value) return

  const isCorrect = chord.id === currentQuestion.value.id
  if (isCorrect) {
    score.value++
    playEffect('correct')
  } else {
    playEffect('incorrect')
  }
  
  quizzHistory.value.push({
    question: { ...currentQuestion.value },
    answer: { ...chord },
    isCorrect,
    isSkipped: false
  })

  userAnswer.value = chord
  isQuestionChanging.value = true
  setTimeout(() => {
    const nextChord = getRandomChord()
    if (nextChord) questions.value.push(nextChord)
    currentQuestionIndex.value++
    userAnswer.value = null
    isQuestionChanging.value = false
    shuffleChords()
    playCurrentQuestion()
  }, DELAYS.FEEDBACK)
}

const skipQuestion = () => {
  if (resultMessage.value) return
  cleanupSideEffects()

  if (!currentQuestion.value) return

  quizzHistory.value.push({
    question: { ...currentQuestion.value },
    answer: null,
    isCorrect: false,
    isSkipped: true
  })

  isQuestionChanging.value = true
  setTimeout(() => {
    const nextChord = getRandomChord()
    if (nextChord) questions.value.push(nextChord)
    currentQuestionIndex.value++
    userAnswer.value = null
    isQuestionChanging.value = false
    shuffleChords()
    playCurrentQuestion()
  }, DELAYS.TRANSITION)
}

const finishQuizz = async () => {
  cleanupSideEffects()
  const { data: { user } } = await supabase.auth.getUser()
  
  if (user && quizzHistory.value.length > 0) {
    isSaving.value = true
    try {
      await supabase.from('training_sessions').insert({
        user_id: user.id,
        score: score.value,
        total_questions: quizzHistory.value.length,
        details: quizzHistory.value,
        settings: {
           mode: 'chord_quizz',
           selected_chords: Array.from(selectedChordIds.value),
           instrument: selectedInstrument.value
        }
      } as any)
    } catch (e) {
      console.error('Failed to save session:', e)
    } finally {
      isSaving.value = false
    }
  }
  view.value = 'result'
}

const resetQuizz = () => {
  cleanupSideEffects()
  view.value = 'settings'
  resultMessage.value = null
}

const handleHeaderBack = (e: Event) => {
  if (view.value !== 'settings') {
    e.preventDefault()
    resetQuizz()
  }
}

// Intercept browser back button
onBeforeRouteLeave((to, from) => {
  if (view.value !== 'settings') {
    resetQuizz()
    return false // Cancel navigation away from this page
  }
})

// === Lifecycle ===

onMounted(async () => {
  await authReady
  loadFromCookie()

  // Initialize default chords on mount IF still empty after load
  if (selectedChordIds.value.size === 0 && QUIZZ_CHORDS.value.length >= 2) {
    selectedChordIds.value.add(QUIZZ_CHORDS.value[0]!.id)
    selectedChordIds.value.add(QUIZZ_CHORDS.value[1]!.id)
    syncToCookie()
  }

  const { getPreferredInstrument } = useAudioSettings()
  let preferred = getPreferredInstrument(userTier.value)
  
  if (preferred === 'steinway' && userTier.value !== "premium") {
    preferred = 'yamaha'
  }
  
  loadSampler(preferred as 'yamaha' | 'steinway')
  
  // Preload feedback images
  const img1 = new Image()
  img1.src = '/quiz_correct.png'
  const img2 = new Image()
  img2.src = '/quiz_incorrect.png'
})

onUnmounted(() => {
  cleanupSideEffects()
})

// === Watchers for Persistence ===
watch([selectedChordIds, parentChordRatio, isReviewWeighted], () => {
  syncToCookie()
}, { deep: true })
</script>

<template>
  <div class="min-h-screen bg-white font-['Noto_Sans_JP'] antialiased" style="backface-visibility: hidden;">
    <div class="min-h-screen flex flex-col items-center max-w-3xl mx-auto relative overflow-hidden">


    <!-- Header -->
    <AppHeader 
      showBack 
      @back="handleHeaderBack"
    />

    <main 
      class="w-full flex-grow flex flex-col scrollbar-hide" 
      :class="view === 'quiz' ? 'p-0 overflow-hidden' : 'px-4 py-6 overflow-y-auto'"
      style="scrollbar-gutter: stable;"
    >
      
      <!-- SETTINGS VIEW -->
      <div v-if="view === 'settings'" class="space-y-8 pb-40">
        <div class="text-center mb-2">
            <h2 class="text-xl font-black text-gray-900">和音クイズ</h2>
            <p class="text-xs text-gray-400 mt-1 font-bold">覚えた色をテストしてみましょう</p>
        </div>

        <!-- Start Button at Top -->
        <div class="px-2 space-y-3">
          <button 
            @click="startQuizz"
            :disabled="selectedChordIds.size === 0"
            class="w-full py-4 bg-gray-900 text-white font-bold rounded-2xl shadow-xl hover:bg-gray-800 transition-all active:scale-95 disabled:opacity-50 disabled:scale-100 flex items-center justify-center space-x-2 border-b-4 border-gray-700"
          >
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z" clip-rule="evenodd" />
            </svg>
            <span>テストを開始する</span>
          </button>

        </div>
        <!-- Chord Selection -->
        <section>
          <div class="flex items-center justify-between mb-4 px-1">
            <label class="text-xs font-bold text-gray-400 uppercase tracking-widest">出題する和音</label>
          </div>
          
          <!-- White Keys -->
          <div class="mb-6">
            <h3 class="text-xs font-bold text-gray-900 mb-3 flex items-center">
              <span class="w-1 h-4 bg-gray-900 rounded-full mr-2"></span>
              白鍵の和音
            </h3>
            <div class="grid grid-cols-2 gap-3">
              <template v-for="chord in whiteKeyChords" :key="chord.id">
                <ChordSelectionButton 
                  :chord="chord" 
                  :selected="selectedChordIds.has(chord.id)"
                  :locked="false"
                  @toggle="toggleChordSelection(chord.id)"
                  @locked-click="navigateToSubscription"
                />
              </template>
            </div>
          </div>

            <div class="flex items-center justify-between mb-4">
              <h3 class="text-xs font-bold text-gray-900 flex items-center">
                <span class="w-1 h-4 bg-gray-900 rounded-full mr-2"></span>
                黒鍵の和音
              </h3>
            </div>
            <div class="grid grid-cols-2 gap-3">
              <ChordSelectionButton 
                v-for="chord in blackKeyChords" 
                :key="chord.id"
                :chord="chord"
                :selected="selectedChordIds.has(chord.id)"
                :locked="!checkAccess('quiz_content_black_keys')"
                @toggle="toggleChordSelection(chord.id)"
                @locked-click="handleLockedClick"
              />
            </div>
        </section>

        <!-- Frequency Settings -->
        <FrequencySettings 
          v-if="isEnabled('quiz_settings_frequency')"
          v-model:parentChordRatio="parentChordRatio"
          v-model:isReviewWeighted="isReviewWeighted"
          :parentChord="parentChord"
          :otherChords="otherChords"
          :otherChordsDisplay="otherChordsDisplay"
          :otherChordsWithWeights="otherChordsWithWeights"
          :selectedCount="selectedChords.length"
        />



      </div>


        <!-- QUIZ VIEW -->
        <div v-if="view === 'quiz'" class="flex-grow w-full flex flex-col bg-white relative">
          
          <!-- Top Progress Bar (Standard) -->
          <div class="fixed top-0 left-0 right-0 z-[60] h-1.5 bg-gray-100/50 backdrop-blur-sm">
            <div class="h-full bg-indigo-500 shadow-[0_0_10px_rgba(99,102,241,0.5)] transition-all duration-500 ease-out"
                :class="{ 'brightness-150 h-2': isQuestionChanging }"
                :style="{ width: '100%' }"></div>
          </div>

          <!-- Minimal Top Info (Standard) -->
          <div class="absolute top-4 left-4 right-4 z-50 flex justify-between items-center pointer-events-none">
            <div class="flex items-center space-x-2">
              <!-- PRO Question Indicator -->
              <div class="flex items-center bg-black/40 backdrop-blur-md rounded-full border border-white/10 shadow-lg overflow-hidden ring-1 ring-black/5 h-8 transition-all duration-300"
                  :class="{ 'scale-125 ring-4 ring-indigo-500/50 bg-indigo-900/60': isQuestionChanging }">
                <div class="px-3 h-full flex items-center bg-white/10 border-r border-white/5">
                  <span class="text-[8px] text-gray-300 font-black uppercase tracking-widest leading-none">Question</span>
                </div>
                <div class="px-4 h-full flex items-center min-w-[3rem] justify-center text-white text-[11px] font-black">
                  Q {{ currentQuestionCount }}
                </div>
              </div>
            </div>

            <button 
              @click="finishQuizz"
              class="pointer-events-auto bg-black/40 backdrop-blur-md text-[10px] text-white font-black rounded-full px-4 h-8 hover:bg-black/50 transition-colors border border-white/10 shadow-lg drop-shadow-sm flex items-center"
            >
              テストを終了
            </button>
          </div>

          <!-- Feedback Overlay (Standard) -->
          <Transition name="feedback-pop">
            <div v-if="userAnswer" class="fixed inset-0 z-[100] flex items-center justify-center pointer-events-none">
              <div v-if="userAnswer && currentQuestion && userAnswer.id === currentQuestion.id" 
                  class="text-[250px] sm:text-[350px] font-black text-blue-500 drop-shadow-[0_0_20px_rgba(59,130,246,0.6)] select-none leading-none">
                ◯
              </div>
              <div v-else 
                  class="text-[250px] sm:text-[350px] font-black text-red-500 drop-shadow-[0_0_20px_rgba(239,68,68,0.6)] select-none leading-none">
                ×
              </div>
            </div>
          </Transition>

          <Transition name="slide-fade" mode="out-in">
            <div :key="currentQuestionIndex" class="flex-grow grid gap-0.5 w-full h-full"
              :style="{ 
                gridTemplateColumns: `repeat(${gridCols}, minmax(0, 1fr))`,
                gridTemplateRows: `repeat(${gridRows}, minmax(0, 1fr))`
              }"
            >
                <template v-for="chord in currentLayoutChords" :key="chord.id">
                  <button
                    @click="submitAnswer(chord)"
                    :disabled="!!userAnswer"
                    class="relative w-full h-full transition-all duration-150 active:scale-95 flex items-center justify-center overflow-hidden"
                    :class="[
                      userAnswer ? (userAnswer.id === chord.id ? 'z-10 ring-inset ring-8 ring-white/50' : 'opacity-20') : 'hover:brightness-105 active:brightness-90'
                    ]"
                    :style="{ backgroundColor: chord.color }"
                  >
                  </button>
                </template>
            </div>
          </Transition>
          
          <!-- Bottom Controls Overlay (Standard) -->
          <div class="absolute bottom-10 left-0 right-0 z-50 flex justify-center items-center space-x-4 pointer-events-none">
            <button 
              v-if="!resultMessage"
              @click="playCurrentQuestion"
              class="pointer-events-auto bg-black/40 backdrop-blur-md text-[10px] text-white font-black rounded-full px-6 py-2.5 hover:bg-black/50 transition-colors border border-white/20 shadow-lg drop-shadow-sm flex items-center space-x-2 active:scale-95"
            >
              <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M4 2a1 1 0 011 1v2.101a7.002 7.002 0 0111.601 2.566 1 1 0 11-1.885.666A5.002 5.002 0 005.999 7H9a1 1 0 010 2H4a1 1 0 01-1-1V3a1 1 0 011-1zm.008 9.057a1 1 0 011.276.61A5.002 5.002 0 0014.001 13H11a1 1 0 110-2h5a1 1 0 011 1v5a1 1 0 11-2 0v-2.101a7.002 7.002 0 01-11.601-2.566 1 1 0 01.61-1.276z" clip-rule="evenodd" />
              </svg>
              <span>再再生</span>
            </button>

            <button 
              v-if="!resultMessage"
              @click="skipQuestion"
              class="pointer-events-auto bg-black/40 backdrop-blur-md px-6 py-2.5 rounded-full text-white font-black hover:bg-black/50 transition-all flex items-center space-x-2 active:scale-95 border border-white/10 shadow-lg drop-shadow-sm"
            >
              <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 5l7 7-7 7M5 5l7 7-7 7" />
              </svg>
              <span class="text-[10px] uppercase tracking-widest">スキップ</span>
            </button>
          </div>
        </div>

      <!-- RESULT VIEW -->
      <div v-if="view === 'result'" class="h-full flex flex-col items-center">
        <div class="mb-8 text-center pt-8">
          <p class="text-xs font-bold text-gray-400 uppercase tracking-widest mb-2">Quiz Finished</p>
          <div class="text-6xl font-black text-gray-900 mb-2">
            <span class="text-blue-500">{{ score }}</span>
            <span class="text-gray-300 text-4xl">/{{ quizzHistory.length }}</span>
          </div>
          <p class="text-lg font-bold text-gray-600 mb-6">
            {{ score === quizzHistory.length ? 'Perfect! 🎉' : score >= quizzHistory.length * 0.8 ? 'Great Job! 👍' : 'Keep Practicing! 💪' }}
          </p>
        </div>

        <!-- Result History List -->
        <div class="w-full bg-gray-50 rounded-3xl border border-gray-100 mb-10 overflow-hidden flex flex-col max-h-[400px]">
          <div class="px-6 py-4 border-b border-gray-100 flex justify-between items-center bg-white/50">
            <span class="text-[10px] font-bold text-gray-400 uppercase tracking-widest">解答履歴</span>
            <span class="text-[10px] font-bold text-gray-900">{{ score }} / {{ quizzHistory.length }} 正解</span>
          </div>
          <div class="flex-grow overflow-y-auto px-4 py-2 space-y-2 scrollbar-hide">
            <div 
              v-for="(history, idx) in quizzHistory" 
              :key="idx"
              class="flex items-center space-x-4 p-3 rounded-2xl bg-white border border-gray-100"
            >
              <div class="w-8 h-8 rounded-full border border-gray-100 flex items-center justify-center text-[10px] font-black text-gray-400 shrink-0">
                {{ idx + 1 }}
              </div>
              
              <!-- Correct Chord Color -->
              <div class="flex-grow flex items-center space-x-3 min-w-0">
                <div class="flex flex-col items-center space-y-1">
                  <div class="w-10 h-10 rounded-lg shadow-sm shrink-0" :style="{ backgroundColor: history.question.color }"></div>
                  <span class="text-[8px] font-bold text-gray-400 leading-none">正解</span>
                </div>
                
                <div class="flex items-center text-gray-400">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                  </svg>
                </div>

                <div class="flex flex-col items-center space-y-1">
                  <div v-if="history.answer" class="w-10 h-10 rounded-lg shadow-sm shrink-0" :style="{ backgroundColor: history.answer.color }"></div>
                  <div v-else class="w-10 h-10 rounded-lg border-2 border-dashed border-gray-200 flex items-center justify-center shrink-0">
                    <span class="text-[8px] text-gray-300 font-bold">SKIP</span>
                  </div>
                  <span class="text-[8px] font-bold text-gray-400 leading-none">回答</span>
                </div>
              </div>

              <!-- Status Mark -->
              <div class="shrink-0 w-10 flex justify-center">
                <div v-if="history.isCorrect" class="text-green-500 font-black text-xl">
                  ○
                </div>
                <div v-else-if="history.isSkipped" class="text-gray-300 font-bold text-sm">
                  −
                </div>
                <div v-else class="text-red-500 font-black text-xl">
                  ×
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="w-full space-y-4 px-6 mb-20">
          <button 
            @click="startQuizz"
            class="w-full py-4 bg-gray-900 text-white font-bold rounded-2xl shadow-lg hover:bg-gray-800 transition-all active:scale-95"
          >
            もう一度挑戦する
          </button>
          <button 
            @click="resetQuizz"
            class="w-full py-4 bg-white text-gray-900 font-bold rounded-2xl border border-gray-200 hover:bg-gray-50 transition-all active:scale-95"
          >
            設定に戻る
          </button>
        </div>
      </div>

    </main>



    </div>
  </div>
</template>

<style scoped>
.scrollbar-hide::-webkit-scrollbar {
    display: none;
}
.scrollbar-hide {
    -ms-overflow-style: none;
    scrollbar-width: none;
}

.fade-enter-active, .fade-leave-active { transition: opacity 0.3s ease; }
.fade-enter-from, .fade-leave-to { opacity: 0; }

.slide-fade-enter-active, .slide-fade-leave-active { 
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}
.slide-fade-enter-from { 
  opacity: 0;
  transform: translateX(10px);
}
.slide-fade-leave-to { 
  opacity: 0;
  transform: translateX(-10px);
}

.feedback-pop-enter-active {
  animation: feedback-pop-in 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}
.feedback-pop-leave-active {
  transition: opacity 0.2s ease;
}
.feedback-pop-enter-from, .feedback-pop-leave-to {
  opacity: 0;
  transform: scale(0.5);
}

@keyframes feedback-pop-in {
  0% { transform: scale(0.5); opacity: 0; }
  50% { transform: scale(1.1); opacity: 1; }
  100% { transform: scale(1); opacity: 1; }
}

@keyframes bounce-in {
  0% { transform: scale(0); opacity: 0; }
  60% { transform: scale(1.1); opacity: 1; }
  100% { transform: scale(1); }
}

@keyframes shake {
  10%, 90% { transform: translate3d(-1px, 0, 0); }
  20%, 80% { transform: translate3d(2px, 0, 0); }
  30%, 50%, 70% { transform: translate3d(-4px, 0, 0); }
  40%, 60% { transform: translate3d(4px, 0, 0); }
}
</style>
