// src/components/ScoreDisplay.vue
<script setup>
import { onMounted, watch, ref, nextTick } from 'vue'
import abcjs from 'abcjs'

const props = defineProps({
  abc: {
    type: String,
    default: ''
  },
  octave: {
    type: Number,
    default: null
  },
  isAnswered: {
    type: Boolean,
    default: true
  },
  placeholderText: {
    type: String,
    default: '?'
  },
  placeholderSubtext: {
    type: String,
    default: '聴き取り中...'
  },
  clef: {
    type: String,
    default: 'treble'
  },
  id: {
    type: String,
    default: 'score-display'
  },
  compact: {
    type: Boolean,
    default: false
  },
  scale: {
    type: Number,
    default: 1
  }
})

const scoreContainer = ref(null)
const uniqueId = `score-${Math.random().toString(36).substr(2, 9)}`

const render = () => {
  if (!props.isAnswered) return

  // Remove chord symbols if present (Home page requirement)
  const cleanAbc = (props.abc || 'y').replace(/"[^"]*"/g, "")
  const clefStr = props.clef === 'bass' ? 'clef=bass' : ''
  
  abcjs.renderAbc(uniqueId, `L:1\nK:C ${clefStr}\n${cleanAbc}`, {
    responsive: null,
    scale: props.scale * (props.compact ? 0.7 : 1),
    paddingtop: props.compact ? 0 : 15,
    paddingbottom: props.compact ? 0 : 15,
    paddingleft: 0,
    paddingright: 0,
    staffwidth: props.compact ? 50 : 70,
    add_classes: false
  })
}

onMounted(() => {
  render()
})

watch(() => [props.abc, props.isAnswered, props.octave], () => {
  if (props.isAnswered) {
    nextTick(render)
  }
})
</script>

<template>
  <div 
    :class="[
      compact 
        ? 'w-20 h-16 bg-gray-50/50 rounded-xl' 
        : 'w-[155px] h-[180px] bg-white rounded-3xl p-4 shadow-sm border border-gray-100'
    ]"
    class="flex flex-col items-center justify-center overflow-hidden relative"
  >
    <!-- Placeholder mask when not answered -->
    <div v-if="!isAnswered" class="absolute inset-0 bg-gray-50/50 backdrop-blur-[1px] flex flex-col items-center justify-center z-20">
      <div class="w-10 h-10 bg-white rounded-2xl flex items-center justify-center shadow-sm mb-2 border border-gray-100">
        <span class="text-xl font-black text-indigo-500">{{ placeholderText }}</span>
      </div>
      <span v-if="placeholderSubtext" class="text-[7px] font-black text-gray-300 uppercase tracking-[0.3em] animate-pulse">
        {{ placeholderSubtext }}
      </span>
    </div>

    <!-- Staff Area -->
    <div v-show="isAnswered" :id="uniqueId" class="w-full flex justify-center items-center pointer-events-none animate-bounce-in" :class="{'scale-125': !compact}"></div>
    
    <slot name="footer" v-if="!compact"></slot>
  </div>
</template>

<style scoped>
@keyframes bounce-in {
  0% { transform: scale(0.3); opacity: 0; }
  50% { transform: scale(1.15); opacity: 1; }
  70% { transform: scale(0.9); }
  100% { transform: scale(1.1); } /* Kept the scale 1.1 from the previous unified design */
}
.animate-bounce-in {
  animation: bounce-in 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.275) both;
}
</style>

// next/src/components/ScoreDisplay.tsx
'use client'

import abcjs from 'abcjs'
import { useEffect, useId, type ReactNode } from 'react'

interface Props {
  abc?: string
  isAnswered?: boolean
  placeholderText?: string
  placeholderSubtext?: string
  clef?: 'treble' | 'bass'
  compact?: boolean
  scale?: number
  footer?: ReactNode
}

export default function ScoreDisplay({
  abc = '',
  isAnswered = true,
  placeholderText = '?',
  placeholderSubtext = '聴き取り中...',
  clef = 'treble',
  compact = false,
  scale = 1,
  footer
}: Props) {
  const elementId = `score-${useId().replace(/:/g, '')}`

  useEffect(() => {
    if (!isAnswered) return
    // Chord symbols are not shown on the home page
    const cleanAbc = (abc || 'y').replace(/"[^"]*"/g, '')
      abcjs.renderAbc(elementId, `L:1\nK:C ${clef === 'bass' ? 'clef=bass' : ''}\n${cleanAbc}`, {
        responsive: undefined,
        scale: scale * (compact ? 0.7 : 1),
        paddingtop: compact ? 0 : 15,
        paddingbottom: compact ? 0 : 15,
        paddingleft: 0,
        paddingright: 0,
        staffwidth: compact ? 50 : 70,
        add_classes: false
      })
  }, [abc, isAnswered, clef, compact, scale, elementId])

  return (
    <div
      className={`flex flex-col items-center justify-center overflow-hidden relative ${
        compact ? 'w-20 h-16 bg-gray-50/50 rounded-xl' : 'w-[155px] h-[180px] bg-white rounded-3xl p-4 shadow-sm border border-gray-100'
      }`}
    >
      {!isAnswered && (
        <div className="absolute inset-0 bg-gray-50/50 backdrop-blur-[1px] flex flex-col items-center justify-center z-20">
          <div className="w-10 h-10 bg-white rounded-2xl flex items-center justify-center shadow-sm mb-2 border border-gray-100">
            <span className="text-xl font-black text-indigo-500">{placeholderText}</span>
          </div>
          {placeholderSubtext && (
            <span className="text-[7px] font-black text-gray-300 uppercase tracking-[0.3em] animate-pulse">{placeholderSubtext}</span>
          )}
        </div>
      )}

      <div
        id={elementId}
        className={`w-full flex justify-center items-center pointer-events-none animate-bounce-in ${compact ? '' : 'scale-125'}`}
        style={{ display: isAnswered ? undefined : 'none' }}
      />

      {!compact && footer}
    </div>
  )
}
